# Generated by Django 3.0.3 on 2020-05-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='')),
                ('Content', models.TextField()),
            ],
        ),
    ]
