# Generated by Django 3.0.3 on 2020-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200506_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
