# Generated by Django 3.0.3 on 2020-05-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200507_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
