# Generated by Django 3.0.3 on 2020-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200507_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
