# Generated by Django 3.0.3 on 2020-05-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200505_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
